from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

class ChatRequest(BaseModel):
    query: str = Field(..., description="The user question to query the knowledge base with.")
    provider: str = Field("groq", description="LLM provider (groq).")
    model: Optional[str] = Field(None, description="Specific model to use. If not specified, default will be used.")
    temperature: float = Field(0.3, ge=0.0, le=2.0, description="Sampling temperature between 0 and 2.")
    top_k: int = Field(5, ge=1, le=20, description="Number of context documents to retrieve.")
    score_threshold: float = Field(0.0, ge=0.0, le=1.0, description="Minimum relevance score threshold.")

class SourceChunk(BaseModel):
    content: str = Field(..., description="The chunk text.")
    source: str = Field(..., description="Source file name.")
    page: int = Field(..., description="Page number/index.")
    score: Optional[float] = Field(None, description="Similarity score (L2 distance or cosine).")

class ChatResponse(BaseModel):
    answer: str = Field(..., description="The grounded response generated by the LLM.")
    sources: List[SourceChunk] = Field(default=[], description="List of document sources used for context.")

class DocumentResponse(BaseModel):
    id: str = Field(..., description="Unique document ID (hash/UUID).")
    filename: str = Field(..., description="Name of the file.")
    uploaded_at: str = Field(..., description="ISO timestamp of when the file was uploaded.")
    file_size: int = Field(..., description="File size in bytes.")
    chunk_count: int = Field(..., description="Number of text chunks generated.")
    embedding_provider: str = Field(..., description="Embedding provider used (huggingface).")

class DeleteResponse(BaseModel):
    success: bool
    message: str

class HealthResponse(BaseModel):
    status: str = Field("healthy")
    langsmith_tracing: bool
    embedding_provider_default: str
    available_providers: Dict[str, Dict[str, Any]]
